apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mysql
    spec:
      containers:
      - image:  mysql:5.6
        name:  mysql
        env:
        - name:  MYSQL_ROOT_PASSWORD
          value:  password
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort:  3306
          name:  mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName:  mysql-pvc
